#!/bin/bash
# Set up a working environment for building the blog.

set -e

blogdir="$(dirname "$(readlink -f "$0")")"
envdir="$blogdir/env"
srcdir="$blogdir/src"

# Create/upgrade the virtual env.
if [ ! -d "$envdir" ]
then
    python3 -m venv "$envdir"
fi

. "$envdir/bin/activate"

pip install -U pip wheel

# Be verbose from now on.
set -x

# Install the requirements.
pip install -Ur "$blogdir/requirements.txt"

# Build static files.
make -C "$srcdir/theme/static" all

# Build the blog.
pelican -s "$srcdir/pelicanconf.py"
